version: '3'
services:
  composer:
    image: composer:latest
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
    restart: never
    entrypoint: composer install
  php:
    image: php:cli-alpine
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ./index.php
  phpunit:
    image: php:cli-alpine
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
